### ISSUE TITLE
How to get list of object by class type

### ISSUE THREAD

**Issue by takaaptech** [nubick/entity-to-playerprefs#2]
For example i want to get a list data of all Levels that saved by our lib.
If would be great if we have a way to get this!
Thank so much!

**Comment by nubick** [comment]
It it not possible to load all saved entities just by some type. Like:
List<Level> levels = PlayerPrefsMapper.LoadAll<Level>();

We have such situation as Unity PlayerPrefs API doesn't have method which allow to get all saved keys. We can't get all PlayerPrefs keys, we can just get value of concrete key or check if this key is presented.

But you can solve this issue by another way. If you have list of levels with some default data and with ids you can use PlayerPrefsMapper.LoadAll(levels) and mapper will load stored data to entities from list. It will process each entity, will take entity key and load all stored data using this key.
