### ISSUE TITLE
it seems to work not well at IL2CPP environment

### ISSUE THREAD

**Issue by freedomWind** [nubick/entity-to-playerprefs#3]
Hey, guys! 
when i compile the app with IL2CPP ,it doesnot work well at both ios and android environment. Seems that the saving operate has some bug.
But when compile with mono, it runs ok.

**Comment by nubick** [comment]
Hi!
I use plugin in all my projects. And I use IL2CPP for all iOS projects which I have. It works good there. I didn't try IL2CPP on Android.
Thanks for info. I will check this when will have a chance.

**Comment by freedomWind** [comment]
the data type I have used contains "int ,string ,float,bool". And under the ios11 environment, I have tried at 2 situations, one  i called the function of saving that it worked not well, another  I noted the saving function that i work well.  The same ways I tried in android environment , and the same result I got.

**Comment by nubick** [comment]
Sorry, I can't reproduce this. If someone provide me example with doesn't work I will check it. All my scenarios work properly in iOS and Android, in IL2CPP and in Mono.
